# To activate this feature, copy this file as .lando.local.yml.
# Further read on configuration file load order is available on:
# https://docs.lando.dev/config/lando.html#base-file
config:
  xdebug: true

services:
  appserver:
    xdebug: true
    overrides:
      environment:
        XDEBUG_MODE:
        PHP_IDE_CONFIG: "serverName=appserver"

events:
  post-start:
    - appserver: export PHP_IDE_CONFIG="serverName=appserver"
